### PR TITLE
Add Haptics

### LINKED ISSUE #69: Add Haptics
- [x] Add haptic manager
- [x] Add haptics on toggling torchlight
- [x] Add haptics on taking picture
- [x] Add haptics on showing result of allergy analysis

### PR DESCRIPTION
**Pull request by poodlepoodle**
#69 

- [x] Add `Utility/HapticUtility.swift`
- [x] Add haptics to `ScannerView` (when toggling torchlight and taking picture)
- [x] Add haptics to `AllergyDetailView` (when showing successful result and unsuccessful result each on)

### CODE REVIEW

**Review by migusdn — DISMISSED** [review]
LGTM

**Review by snacknam — DISMISSED** [review]
LGTM!👍🏻

**Review by ckyeon — DISMISSED** [review]
LGTM

**Review by migusdn — APPROVED** [review]
LGTM

**Review by ckyeon — APPROVED** [review]
LGTM

**Review by snacknam — APPROVED** [review]
LGTM!

**Pull request merged**
