### PR TITLE
Add ScannerView Logics

### LINKED ISSUE #39: Add ScannerView Logics
- [x] Refactor with VisionKit
- [x] Add pinch-zoom action
- [x] Add tap-focusing action

### PR DESCRIPTION
**Pull request by poodlepoodle**
#39 

- refactored `ScannerView` with `VisionKit`.
- added pinch and tap action to `ScannerView`.
- added custom bounding box ui to `ScannerView`
- refactored logics to `ScannerViewController`

---

image

### CODE REVIEW

**Review by ckyeon — DISMISSED** [review]
Good ~

**Review by migusdn — APPROVED** [review]
LGTM

**Review by snacknam — APPROVED** [review]
Great Work! 👍🏻

**Review by ckyeon — APPROVED** [review]
Re: LGTM👍

**Pull request merged**
