### PR TITLE
Block Landscape Mode

### LINKED ISSUE #41: Block Landscape Mode
- [ ] block landscape mode

### PR DESCRIPTION
**Pull request by poodlepoodle**
#41 

- block landscape mode in `.pbxproj`

### CODE REVIEW

**Review by snacknam — APPROVED** [review]
GOOD BOY!

**Review by ckyeon — APPROVED** [review]
LGTM

**Review by migusdn — APPROVED** [review]
'APPROVE' performed by Xcode.

**Comment by migusdn** [comment]
LGTM

**Pull request merged**
